name: Read the Docs

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: macos-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        uses: sphinx-notes/pages@v3
        with:
          python_version: 3.12
